name: Python Script with API Key

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  Run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Using GitHub secret for API_KEY
        run: python Main.py
